# Generated by Django 4.2.4 on 2023-08-04 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portafolio", "0002_rename_description_profile_descripcion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="profile_picture",
            new_name="foto",
        ),
    ]
