# Generated by Django 4.2.4 on 2023-08-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portafolio", "0003_rename_profile_picture_profile_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("foto", models.ImageField(upload_to="proyectos/")),
                ("enlace_pagina", models.URLField()),
                ("enlace_github", models.URLField()),
            ],
        ),
    ]
